export const appActionKeys = {
  LOGIN_STATUS: {
    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
  },

  LOGOUT_STATUS: {
    LOGOUT_START: 'LOGOUT_START',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAIL: 'LOGOUT_FAIL',
  },

  CHANGE_KEY_MENU: {
    CHANGE_KEY_MENU_START: 'CHANGE_KEY_MENU_START',
    CHANGE_KEY_MENU_SUCCESS: 'CHANGE_KEY_MENU_SUCCESS',
    CHANGE_KEY_MENU_FAIL: 'CHANGE_KEY_MENU_FAIL',
  },

  CHANGE_SUB_KEY_MENU: {
    CHANGE_SUB_KEY_MENU_START: 'CHANGE_SUB_KEY_MENU_START',
    CHANGE_SUB_KEY_MENU_SUCCESS: 'CHANGE_SUB_KEY_MENU_SUCCESS',
    CHANGE_SUB_KEY_MENU_FAIL: 'CHANGE_SUB_KEY_MENU_FAIL',
  },

  SOCKET: {
    SOCKET_CONNECT_START: 'SOCKET_CONNECT_START',
    SOCKET_CONNECT_SUCCESS: 'SOCKET_CONNECT_SUCCESS',
    SOCKET_CONNECT_FAIL: 'SOCKET_CONNECT_FAIL',

    SOCKET_DISCONNECT_START: 'SOCKET_DISCONNECT_START',
    SOCKET_DISCONNECT_SUCCESS: 'SOCKET_DISCONNECT_SUCCESS',
    SOCKET_DISCONNECT_FAIL: 'SOCKET_DISCONNECT_FAIL',
  },

  ERROR: {
    ERROR_START: 'ERROR_START',
    ERROR_SUCCESS: 'ERROR_SUCCESS',
    ERROR_FAIL: 'ERROR_FAIL',
  },
};
