export const userActionKeys = {
  CHAT_STATUS: {
    SELECTED_CHAT: 'SELECTED_CHAT',
  },

  NOTIFICATIONS: {
    FRIENDS: 'FRIENDS',
    GROUPS: 'GROUPS',
    MESSAGES: 'MESSAGES',
    CHAT: 'CHAT',
    FETCH_NOTIFICATIONS_FRIENDS_FUNC: 'FETCH_NOTIFICATIONS_FRIENDS_FUNC',
    FETCH_NOTIFICATIONS_CHAT_FUNC: 'FETCH_NOTIFICATIONS_CHAT_FUNC',
  },

  MESSAGES: {
    SEND_MESSAGE_FUNC: 'SEND_MESSAGE_FUNC',
    FETCH_MESSAGES_FUNC: 'FETCH_MESSAGES_FUNC',
  },
};
